In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv('MY2022 Fuel Consumption Ratings.csv')

In [4]:
df.head()

,Model Year,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption (City (L/100 km),Fuel Consumption(Hwy (L/100 km)),Fuel Consumption(Comb (L/100 km)),Fuel Consumption(Comb (mpg)),CO2 Emissions(g/km),CO2 Rating,Smog Rating
0,2022,Acura,ILX,Compact,2.4,4,AM8,Z,9.9,7.0,8.6,33,200,6,3
1,2022,Acura,MDX SH-AWD,SUV: Small,3.5,6,AS10,Z,12.6,9.4,11.2,25,263,4,5
2,2022,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,Z,11.0,8.6,9.9,29,232,5,6
3,2022,Acura,RDX SH-AWD A-SPEC,SUV: Small,2.0,4,AS10,Z,11.3,9.1,10.3,27,242,5,6
4,2022,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,11.2,8.0,9.8,29,230,5,7

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 946 entries, 0 to 945
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Model Year                         946 non-null    int64
 1   Make                               946 non-null    object
 2   Model                              946 non-null    object
 3   Vehicle Class                      946 non-null    object
 4   Engine Size(L)                     946 non-null    float64
 5   Cylinders                          946 non-null    int64
 6   Transmission                       946 non-null    object
 7   Fuel Type                          946 non-null    object
 8   Fuel Consumption (City (L/100 km)  946 non-null    float64
 9   Fuel Consumption(Hwy (L/100 km))   946 non-null    float64
 10  Fuel Consumption(Comb (L/100 km))  946 non-null    float64
 11  Fuel Consumption(Comb (mpg))       946 non-null    int64
 12  CO2 Emissions(g/km)                946 non-null    int64
 13  CO2 Rating                         946 non-null    int64
 14  Smog Rating                        946 non-null    int64
dtypes: float64(4), int64(6), object(5)
memory usage: 111.0+ KB

In [6]:
df.duplicated().sum()

0

In [7]:
df.columns

Index(['Model Year', 'Make', 'Model', 'Vehicle Class', 'Engine Size(L)',
       'Cylinders', 'Transmission', 'Fuel Type',
       'Fuel Consumption (City (L/100 km)', 'Fuel Consumption(Hwy (L/100 km))',
       'Fuel Consumption(Comb (L/100 km))', 'Fuel Consumption(Comb (mpg))',
       'CO2 Emissions(g/km)', 'CO2 Rating', 'Smog Rating'],
      dtype='object')

In [8]:
df.drop(columns=['Model Year','Fuel Consumption (City (L/100 km)','Fuel Consumption(Hwy (L/100 km))','Fuel Consumption(Comb (mpg))'],axis=1,inplace=True)

In [9]:
df.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption(Comb (L/100 km)),CO2 Emissions(g/km),CO2 Rating,Smog Rating
0,Acura,ILX,Compact,2.4,4,AM8,Z,8.6,200,6,3
1,Acura,MDX SH-AWD,SUV: Small,3.5,6,AS10,Z,11.2,263,4,5
2,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,Z,9.9,232,5,6
3,Acura,RDX SH-AWD A-SPEC,SUV: Small,2.0,4,AS10,Z,10.3,242,5,6
4,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,9.8,230,5,7

In [10]:
l=["make","model","vehicle","engine_size","cylinders","transmission","fueltype","fuel_consumption","co2emission","co2 rating","SmogRating"]

In [11]:
l

['make',
 'model',
 'vehicle',
 'engine_size',
 'cylinders',
 'transmission',
 'fueltype',
 'fuel_consumption',
 'co2emission',
 'co2 rating',
 'SmogRating']

In [12]:
df.rename(columns={i:j for i,j in zip(df.columns,l)},inplace=True)

In [13]:
df.head()

,make,model,vehicle,engine_size,cylinders,transmission,fueltype,fuel_consumption,co2emission,co2 rating,SmogRating
0,Acura,ILX,Compact,2.4,4,AM8,Z,8.6,200,6,3
1,Acura,MDX SH-AWD,SUV: Small,3.5,6,AS10,Z,11.2,263,4,5
2,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,Z,9.9,232,5,6
3,Acura,RDX SH-AWD A-SPEC,SUV: Small,2.0,4,AS10,Z,10.3,242,5,6
4,Acura,TLX SH-AWD,Compact,2.0,4,AS10,Z,9.8,230,5,7

In [14]:
cat=[]
num=[]
for i in df.columns:
    if type(df[i].iloc[0]) == str:
        cat.append(i)
    else:
        num.append(i)

In [15]:
print("the cat data :{}, \n the num data:{}".format(cat,num))

the cat data :['make', 'model', 'vehicle', 'transmission', 'fueltype'],
 the num data:['engine_size', 'cylinders', 'fuel_consumption', 'co2emission', 'co2 rating', 'SmogRating']

In [16]:
df=df[['make','model','vehicle','transmission','fueltype','engine_size', 'cylinders','fuel_consumption','co2emission','co2 rating','SmogRating']]

In [17]:
df

,make,model,vehicle,transmission,fueltype,engine_size,cylinders,fuel_consumption,co2emission,co2 rating,SmogRating
0,Acura,ILX,Compact,AM8,Z,2.4,4,8.6,200,6,3
1,Acura,MDX SH-AWD,SUV: Small,AS10,Z,3.5,6,11.2,263,4,5
2,Acura,RDX SH-AWD,SUV: Small,AS10,Z,2.0,4,9.9,232,5,6
3,Acura,RDX SH-AWD A-SPEC,SUV: Small,AS10,Z,2.0,4,10.3,242,5,6
4,Acura,TLX SH-AWD,Compact,AS10,Z,2.0,4,9.8,230,5,7
...,...,...,...,...,...,...,...,...,...,...,...
941,Volvo,XC40 T5 AWD,SUV: Small,AS8,Z,2.0,4,9.4,219,5,5
942,Volvo,XC60 B5 AWD,SUV: Small,AS8,Z,2.0,4,9.4,219,5,5
943,Volvo,XC60 B6 AWD,SUV: Small,AS8,Z,2.0,4,9.9,232,5,7
944,Volvo,XC90 T5 AWD,SUV: Standard,AS8,Z,2.0,4,10.1,236,5,5
945,Volvo,XC90 T6 AWD,SUV: Standard,AS8,Z,2.0,4,10.8,252,5,7

In [18]:
x=df.drop("fuel_consumption",axis=1)

In [19]:
y=df["fuel_consumption"]

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe=OneHotEncoder(sparse=False,handle_unknown="ignore")

In [22]:
x_dup=pd.DataFrame(ohe.fit_transform(df.iloc[:,:5]),columns=ohe.get_feature_names_out())

In [23]:
x_dup

,make_Acura,make_Alfa Romeo,make_Aston Martin,make_Audi,make_BMW,make_Bentley,make_Bugatti,make_Buick,make_Cadillac,make_Chevrolet,...,transmission_AV6,transmission_AV7,transmission_AV8,transmission_M5,transmission_M6,transmission_M7,fueltype_D,fueltype_E,fueltype_X,fueltype_Z
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [24]:
x.drop(columns=['make', 'model', 'vehicle', 'transmission', 'fueltype'],axis=1,inplace=True)

In [25]:
x

     engine_size  cylinders  co2emission  co2 rating  SmogRating
0            2.4          4          200           6           3
1            3.5          6          263           4           5
2            2.0          4          232           5           6
3            2.0          4          242           5           6
4            2.0          4          230           5           7
..           ...        ...          ...         ...         ...
941          2.0          4          219           5           5
942          2.0          4          219           5           5
943          2.0          4          232           5           7
944          2.0          4          236           5           5
945          2.0          4          252           5           7

[946 rows x 5 columns]

In [26]:
x=pd.concat([x,x_dup],axis=1)

In [27]:
x

,engine_size,cylinders,co2emission,co2 rating,SmogRating,make_Acura,make_Alfa Romeo,make_Aston Martin,make_Audi,make_BMW,...,transmission_AV6,transmission_AV7,transmission_AV8,transmission_M5,transmission_M6,transmission_M7,fueltype_D,fueltype_E,fueltype_X,fueltype_Z
0,2.4,4,200,6,3,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3.5,6,263,4,5,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2.0,4,232,5,6,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,2.0,4,242,5,6,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,2.0,4,230,5,7,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,2.0,4,219,5,5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
942,2.0,4,219,5,5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
943,2.0,4,232,5,7,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
944,2.0,4,236,5,5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
945,2.0,4,252,5,7,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=24)

In [29]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [30]:
model.fit(x_train,y_train)

LinearRegression()

In [31]:
model.score(x_train,y_train)

0.9994552208844537

In [32]:
model.score(x_test,y_test)

-8288438932448303.0

In [33]:
from sklearn.ensemble import RandomForestRegressor
RFR=RandomForestRegressor()

In [34]:
RFR.fit(x_train,y_train)

RandomForestRegressor()

In [35]:
RFR.score(x_train,y_train)

0.9975349395253352

In [36]:
RFR.score(x_test,y_test)

0.9923128130921485

In [37]:
import joblib

In [38]:
joblib.dump(ohe,"five_joblib")

['five_joblib']

In [39]:
joblib.dump(RFR,"RFR.pkl")

['RFR.pkl']

In [40]:
check=df.copy()

In [41]:
check=check.head(1)

In [42]:
check

,make,model,vehicle,transmission,fueltype,engine_size,cylinders,fuel_consumption,co2emission,co2 rating,SmogRating
0,Acura,ILX,Compact,AM8,Z,2.4,4,8.6,200,6,3

In [43]:
check.drop("fuel_consumption",axis=1,inplace=True)

In [44]:
check

,make,model,vehicle,transmission,fueltype,engine_size,cylinders,co2emission,co2 rating,SmogRating
0,Acura,ILX,Compact,AM8,Z,2.4,4,200,6,3

In [45]:
one_hot=joblib.load("five_joblib")

In [46]:
one_hot

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [47]:
l=one_hot.transform(check.iloc[:,:5])

In [48]:
l

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [49]:
c=one_hot.get_feature_names_out()

In [50]:
c

array(['make_Acura', 'make_Alfa Romeo', 'make_Aston Martin', 'make_Audi',
       'make_BMW', 'make_Bentley', 'make_Bugatti', 'make_Buick',
       'make_Cadillac', 'make_Chevrolet', 'make_Chrysler', 'make_Dodge',
       'make_FIAT', 'make_Ford', 'make_GMC', 'make_Genesis', 'make_Honda',
       'make_Hyundai', 'make_Infiniti', 'make_Jaguar', 'make_Jeep',
       'make_Kia', 'make_Lamborghini', 'make_Land Rover', 'make_Lexus',
       'make_Lincoln', 'make_MINI', 'make_Maserati', 'make_Mazda',
       'make_Mercedes-Benz', 'make_Mitsubishi', 'make_Nissan',
       'make_Porsche', 'make_Ram', 'make_Rolls-Royce', 'make_Subaru',
       'make_Toyota', 'make_Volkswagen', 'make_Volvo', 'model_1500',
       'model_1500 4X4', 'model_1500 4X4 EcoDiesel', 'model_1500 4X4 TRX',
       'model_1500 4X4 eTorque', 'model_1500 Classic',
       'model_1500 Classic 4X4', 'model_1500 EcoDiesel',
       'model_1500 HFE EcoDiesel', 'model_1500 HFE eTorque',
       'model_1500 eTorque', 'model_300', 'model_300 AWD',
       'model_330i xDrive Sedan', 'model_430i xDrive Cabriolet',
       'model_430i xDrive Coupe', 'model_4Runner 4WD',
       'model_4Runner 4WD (Part-Time 4WD) ', 'model_500X AWD',
       'model_530i xDrive Sedan', 'model_540i xDrive Sedan',
       'model_718 Boxster', 'model_718 Boxster GTS 4.0',
       'model_718 Boxster S', 'model_718 Boxster T', 'model_718 Cayman',
       'model_718 Cayman GT4', 'model_718 Cayman GTS 4.0',
       'model_718 Cayman S', 'model_718 Cayman T', 'model_718 Spyder',
       'model_750Li xDrive Sedan', 'model_750i xDrive Sedan',
       'model_911 Carrera', 'model_911 Carrera 4',
       'model_911 Carrera 4 Cabriolet', 'model_911 Carrera 4 GTS',
       'model_911 Carrera 4 GTS Cabriolet', 'model_911 Carrera 4S',
       'model_911 Carrera 4S Cabriolet', 'model_911 Carrera Cabriolet',
       'model_911 Carrera GTS', 'model_911 Carrera GTS Cabriolet',
       'model_911 Carrera S', 'model_911 Carrera S Cabriolet',
       'model_911 GT3', 'model_911 GT3 Touring', 'model_911 Targa 4',
       'model_911 Targa 4 GTS', 'model_911 Targa 4S', 'model_911 Turbo',
       'model_911 Turbo Cabriolet', 'model_911 Turbo S',
       'model_911 Turbo S Cabriolet', 'model_A 220 4MATIC Sedan',
       'model_A 250 4MATIC Hatch', 'model_A3 Sedan 40 TFSI quattro',
       'model_A4 Sedan 40 TFSI quattro', 'model_A4 Sedan 45 TFSI quattro',
       'model_A4 allroad 45 TFSI quattro',
       'model_A5 Cabriolet 45 TFSI quattro',
       'model_A5 Coupe 45 TFSI quattro',
       'model_A5 Sportback 45 TFSI quattro',
       'model_A6 Sedan 45 TFSI quattro', 'model_A6 Sedan 55 TFSI quattro',
       'model_A6 allroad 55 TFSI quattro',
       'model_A7 Sportback 55 TFSI quattro',
       'model_A8 L Sedan 55 TFSI quattro', 'model_AMG A 35 4MATIC Hatch',
       'model_AMG A 35 4MATIC Sedan', 'model_AMG C 43 4MATIC Cabriolet',
       'model_AMG C 43 4MATIC Coupe', 'model_AMG CLA 35 4MATIC Coupe',
       'model_AMG CLA 45 4MATIC Coupe', 'model_AMG CLS 53 4MATIC+ Coupe',
       'model_AMG E 53 4MATIC+ Cabriolet', 'model_AMG E 53 4MATIC+ Coupe',
       'model_AMG E 53 4MATIC+ Sedan', 'model_AMG GLA 35 4MATIC SUV',
       'model_AMG GLA 45 4MATIC SUV', 'model_AMG GLB 35 4MATIC SUV',
       'model_AMG GLC 43 4MATIC Coupe', 'model_AMG GLC 43 4MATIC SUV',
       'model_AMG GLE 53 4MATIC+ Coupe', 'model_AMG GLE 53 4MATIC+ SUV',
       'model_AMG GT 53 4MATIC+ Coupe', 'model_Acadia',
       'model_Acadia AWD', 'model_Accord', 'model_Accord Hybrid',
       'model_Accord Hybrid Sport/Touring', 'model_Accord Sport/Touring',
       'model_Alpina B7', 'model_Alpina B8 Gran Coupe',
       'model_Alpina XB7', 'model_Altima AWD',
       'model_Altima AWD SR/Platinum', 'model_Armada 4WD',
       'model_Ascent AWD', 'model_Atlas 4MOTION',
       'model_Atlas Cross Sport 4MOTION', 'model_Aventador Countach',
       'model_Aventador Coupe', 'model_Aventador Roadster',
       'model_Aviator AWD', 'model_BRZ', 'model_Bentayga',
       'model_Bentayga Speed', 'model_Blazer', 'model_Blazer AWD',
       'model_Bronco 4WD', 'model_Bronco Badlands 4WD',
       'model_Bronco Black Diamond 4WD', 'model_Bronco Sasquatch 4WD',
       'model_Bronco Sport 4WD', 'model_C 300 4MATIC Cabriolet',
       'model_C 300 4MATIC Coupe', 'model_C-HR',
       'model_CLA 250 4MATIC Coupe', 'model_CLS 450 4MATIC Coupe',
       'model_CR-V', 'model_CR-V AWD', 'model_CT4', 'model_CT4 AWD',
       'model_CT4-V', 'model_CT4-V AWD', 'model_CT4-V Blackwing',
       'model_CT5', 'model_CT5 AWD', 'model_CT5-V', 'model_CT5-V AWD',
       'model_CT5-V Blackwing', 'model_CX-3', 'model_CX-3 (SIL)',
       'model_CX-3 4WD', 'model_CX-30 4WD', 'model_CX-30 Turbo 4WD',
       'model_CX-5 4WD', 'model_CX-5 4WD (Cylinder Deactivation)',
       'model_CX-5 Turbo 4WD', 'model_CX-9 4WD', 'model_Camaro',
       'model_Camaro SS', 'model_Camaro ZL1', 'model_Camry AWD SE',
       'model_Camry AWD XSE', 'model_Camry Hybrid LE',
       'model_Camry Hybrid SE/XLE/XSE', 'model_Camry LE/SE',
       'model_Camry TRD', 'model_Camry XSE', 'model_Camry XSE V6',
       'model_Canyon', 'model_Canyon 4WD', 'model_Carnival',
       'model_Cayenne', 'model_Cayenne Coupe', 'model_Cayenne GTS',
       'model_Cayenne GTS Coupe', 'model_Cayenne S',
       'model_Cayenne S Coupe', 'model_Cayenne Turbo',
       'model_Cayenne Turbo Coupe', 'model_Cayenne Turbo GT',
       'model_Challenger', 'model_Challenger (MDS)',
       'model_Challenger AWD', 'model_Challenger SRT Hellcat',
       'model_Challenger SRT Hellcat Widebody',
       'model_Challenger Widebody', 'model_Challenger Widebody (MDS)',
       'model_Charger', 'model_Charger (MDS)', 'model_Charger AWD',
       'model_Charger SRT Hellcat Widebody',
       'model_Charger Widebody (MDS)', 'model_Cherokee',
       'model_Cherokee 4X4 Active Drive I',
       'model_Cherokee 4X4 Active Drive Lock', 'model_Chiron',
       'model_Chiron Pur Sport', 'model_Chiron Super Sport',
       'model_Civic Hatchback', 'model_Civic Sedan',
       'model_Civic Sedan Si', 'model_Colorado', 'model_Colorado 4WD',
       'model_Colorado ZR2 4WD', 'model_Compass', 'model_Compass 4X4',
       'model_Continental GT', 'model_Continental GT Convertible',
       'model_Continental GT Convertible Speed',
       'model_Continental GT Speed', 'model_Cooper 3 Door',
       'model_Cooper 5 Door', 'model_Cooper Convertible',
       'model_Cooper Countryman ALL4', 'model_Cooper S 3 Door',
       'model_Cooper S 5 Door', 'model_Cooper S Clubman ALL4',
       'model_Cooper S Convertible', 'model_Cooper S Countryman ALL4',
       'model_Corolla', 'model_Corolla Apex Edition',
       'model_Corolla Cross', 'model_Corolla Cross AWD',
       'model_Corolla Hatchback', 'model_Corolla Hybrid',
       'model_Corolla XLE', 'model_Corolla XSE', 'model_Corsair AWD',
       'model_Corvette', 'model_Crosstrek AWD', 'model_Cullinan',
       'model_Cullinan Black Badge', 'model_DB11 V12', 'model_DB11 V8',
       'model_DBS V12', 'model_DBX V8', 'model_Defender 110 5.0L V8',
       'model_Defender 110 P300', 'model_Defender 110 P400',
       'model_Defender 90 5.0L V8', 'model_Defender 90 P300',
       'model_Defender 90 P400', 'model_Discovery P300',
       'model_Discovery P360', 'model_Durango AWD',
       'model_Durango AWD SRT', 'model_E 350 4MATIC Sedan',
       'model_E 450 4MATIC All-Terrain Wagon',
       'model_E 450 4MATIC Cabriolet', 'model_E 450 4MATIC Coupe',
       'model_E 450 4MATIC Sedan', 'model_E-PACE P250',
       'model_E-PACE P300', 'model_ES 250 AWD', 'model_ES 300h',
       'model_ES 350', 'model_ES 350 F SPORT', 'model_Eclipse Cross 4WD',
       'model_EcoSport AWD', 'model_Edge AWD', 'model_Elantra',
       'model_Elantra (ISG)', 'model_Elantra Hybrid Blue',
       'model_Elantra N', 'model_Enclave', 'model_Enclave AWD',
       'model_Encore', 'model_Encore AWD', 'model_Encore GX',
       'model_Encore GX AWD', 'model_Envision', 'model_Envision AWD',
       'model_Equinox', 'model_Equinox AWD', 'model_Escalade 4WD',
       'model_Escalade 4WD (No Stop-Start)', 'model_Escape',
       'model_Escape AWD', 'model_Escape Hybrid',
       'model_Escape Hybrid AWD', 'model_Expedition 4X4',
       'model_Expedition 4X4 (Without Stop-Start)',
       'model_Expedition Timberline 4X4',
       'model_Expedition Timberline 4X4 (Without Stop-Start)',
       'model_Explorer AWD', 'model_Explorer AWD (Without Stop-Start)',
       'model_Explorer Hybrid AWD', 'model_Explorer Timberline AWD',
       'model_Explorer Timberline AWD (Without Stop-Start)',
       'model_F-150', 'model_F-150 (Without Stop-Start)',
       'model_F-150 4X4', 'model_F-150 4X4 (Without Stop-Start)',
       'model_F-150 4X4 FFV', 'model_F-150 4X4 FFV (Without Stop-Start)',
       'model_F-150 FFV', 'model_F-150 FFV (Without Stop-Start)',
       'model_F-150 Hybrid', 'model_F-150 Hybrid 4X4',
       'model_F-150 Raptor 37 4X4',
       'model_F-150 Raptor 37 4X4 (Without Stop-Start)',
       'model_F-150 Raptor 4X4',
       'model_F-150 Raptor 4X4 (Without Stop-Start)',
       'model_F-150 Tremor 4X4',
       'model_F-150 Tremor 4X4 (Without Stop-Start)',
       'model_F-TYPE P450 Convertible',
       'model_F-TYPE P450 Convertible AWD', 'model_F-TYPE P450 Coupe',
       'model_F-TYPE P450 Coupe AWD', 'model_F-TYPE R Convertible AWD',
       'model_F-TYPE R Coupe AWD', 'model_Flying Spur',
       'model_Forester AWD', 'model_Forester Wilderness AWD',
       'model_Forte', 'model_Forte 5', 'model_Frontier',
       'model_Frontier 4WD', 'model_G70 AWD', 'model_G80 AWD',
       'model_G90 AWD', 'model_GLA 250 4MATIC SUV',
       'model_GLB 250 4MATIC SUV', 'model_GLC 300 4MATIC Coupe',
       'model_GLC 300 4MATIC SUV', 'model_GLE 350 4MATIC SUV',
       'model_GLE 450 4MATIC Coupe', 'model_GLE 450 4MATIC SUV',
       'model_GLS 450 4MATIC SUV', 'model_GR 86', 'model_GR Supra 2.0',
       'model_GR Supra 3.0', 'model_GT', 'model_GV70 AWD',
       'model_GV80 AWD', 'model_GX 460', 'model_Ghibli GT',
       'model_Ghibli Modena', 'model_Ghibli Modena AWD',
       'model_Ghibli Trofeo', 'model_Ghost', 'model_Ghost Black Badge',
       'model_Ghost EWB', 'model_Giulia', 'model_Giulia AWD',
       'model_Giulia Quadrifoglio', 'model_Gladiator 4X4',
       'model_Gladiator 4X4 EcoDiesel',
       'model_Gladiator 4X4 Rubicon EcoDiesel', 'model_Golf GTI',
       'model_Golf R', 'model_Grand Caravan', 'model_Grand Cherokee 4X4',
       'model_Grand Cherokee L 4X4', 'model_Grand Cherokee WK 4X4',
       'model_Grand Wagoneer 4X4', 'model_HR-V', 'model_HR-V AWD',
       'model_Highlander AWD', 'model_Highlander Hybrid AWD',
       'model_Highlander Hybrid AWD Limited/Platinum',
       'model_Huracan evo Coupe', 'model_Huracan evo Coupe AWD',
       'model_Huracan evo Spyder', 'model_Huracan evo Spyder AWD',
       'model_ILX', 'model_IONIQ', 'model_IONIQ Blue', 'model_IS 300',
       'model_IS 300 AWD', 'model_IS 350 AWD', 'model_IS 500',
       'model_Impreza 4-Door AWD', 'model_Impreza 5-Door AWD',
       'model_Jetta', 'model_Jetta GLI', 'model_Jetta SE/SEL',
       'model_John Cooper Works 3 Door',
       'model_John Cooper Works Clubman ALL4',
       'model_John Cooper Works Convertible',
       'model_John Cooper Works Countryman ALL4', 'model_K5',
       'model_K5 AWD', 'model_Kicks', 'model_Kona', 'model_Kona AWD',
       'model_Kona N', 'model_LC 500', 'model_LC 500 Convertible',
       'model_LC 500h', 'model_LS 500 AWD', 'model_LS 500h AWD',
       'model_LX 600', 'model_Legacy AWD', 'model_Levante GT',
       'model_Levante Modena', 'model_Levante Modena V8',
       'model_Levante Trofeo', 'model_M235i xDrive Gran Coupe',
       'model_M240i xDrive Coupe', 'model_M3 Competition Sedan',
       'model_M3 Competition Sedan M xDrive', 'model_M3 Sedan',
       'model_M340i xDrive Sedan',
       'model_M4 Competition Cabriolet M xDrive',
       'model_M4 Competition Coupe',
       'model_M4 Competition Coupe M xDrive', 'model_M4 Coupe',
       'model_M440i xDrive Cabriolet', 'model_M440i xDrive Coupe',
       'model_M440i xDrive Gran Coupe', 'model_M5 CS',
       'model_M5 Competition', 'model_M5 Sedan',
       'model_M550i xDrive Sedan', 'model_M760i xDrive Sedan',
       'model_M8 Cabriolet', 'model_M8 Cabriolet Competition',
       'model_M8 Coupe', 'model_M8 Coupe Competition',
       'model_M8 Gran Coupe', 'model_M8 Gran Coupe Competition',
       'model_M850i xDrive Cabriolet', 'model_M850i xDrive Coupe',
       'model_M850i xDrive Gran Coupe', 'model_MC20', 'model_MDX SH-AWD',
       'model_MX-5', 'model_MX-5 (SIL)', 'model_Macan', 'model_Macan GTS',
       'model_Macan S', 'model_Malibu', 'model_Maverick AWD',
       'model_Maverick Hybrid', 'model_Maxima',
       'model_Maybach S 580 4MATIC Sedan', 'model_Mazda3 4-Door',
       'model_Mazda3 4-Door (SIL)', 'model_Mazda3 4-Door 4WD',
       'model_Mazda3 4-Door Turbo 4WD', 'model_Mazda3 5-Door',
       'model_Mazda3 5-Door (SIL)', 'model_Mazda3 5-Door 4WD',
       'model_Mazda3 5-Door Turbo 4WD', 'model_Metris Cargo Van',
       'model_Metris Cargo Van LWB', 'model_Metris Passenger Van',
       'model_Mirage', 'model_Murano AWD', 'model_Mustang',
       'model_Mustang (High Performance)', 'model_Mustang Convertible',
       'model_Mustang Convertible (High Performance)',
       'model_Mustang Mach 1', 'model_NX 250 AWD', 'model_NX 350 AWD',
       'model_NX 350 AWD F SPORT', 'model_NX 350h AWD',
       'model_Nautilus AWD', 'model_Navigator 4X4', 'model_Niro',
       'model_Niro FE', 'model_Niro Touring', 'model_Odyssey',
       'model_Outback AWD', 'model_Outback Wilderness AWD',
       'model_Outlander 4WD', 'model_Pacifica', 'model_Pacifica AWD',
       'model_Palisade AWD', 'model_Panamera', 'model_Panamera 4',
       'model_Panamera 4 Executive', 'model_Panamera 4 ST',
       'model_Panamera 4S', 'model_Panamera 4S Executive',
       'model_Panamera 4S ST', 'model_Panamera GTS',
       'model_Panamera GTS ST', 'model_Panamera Turbo S',
       'model_Panamera Turbo S Executive', 'model_Panamera Turbo S ST',
       'model_Passat', 'model_Passport AWD', 'model_Pathfinder 4WD',
       'model_Phantom', 'model_Phantom EWB', 'model_Pilot AWD',
       'model_Pilot AWD TrailSport', 'model_Prius', 'model_Prius AWD',
       'model_ProMaster City', 'model_Q3 40 TFSI quattro',
       'model_Q3 45 TFSI quattro', 'model_Q5 40 TFSI quattro',
       'model_Q5 45 TFSI quattro', 'model_Q5 Sportback 45 TFSI quattro',
       'model_Q50 AWD', 'model_Q50 AWD Red Sport', 'model_Q60 AWD',
       'model_Q60 AWD Red Sport', 'model_Q7 45 TFSI quattro',
       'model_Q7 55 TFSI quattro', 'model_Q8 55 TFSI quattro',
       'model_QX50 AWD', 'model_QX55 AWD', 'model_QX60 AWD',
       'model_QX80 4WD', 'model_Qashqai', 'model_Qashqai AWD',
       'model_Quattroporte GT', 'model_Quattroporte Modena',
       'model_Quattroporte Modena AWD', 'model_Quattroporte Trofeo',
       'model_R8 Coupe Performance', 'model_R8 Coupe Performance quattro',
       'model_R8 Spyder Performance',
       'model_R8 Spyder Performance quattro', 'model_RAV4',
       'model_RAV4 (Stop/Start)', 'model_RAV4 AWD',
       'model_RAV4 AWD (Stop/Start)', 'model_RAV4 AWD LE',
       'model_RAV4 AWD TRD Off-Road', 'model_RAV4 Hybrid AWD',
       'model_RC 300 AWD', 'model_RC 350 AWD', 'model_RC F',
       'model_RDX SH-AWD', 'model_RDX SH-AWD A-SPEC',
       'model_RS 5 Coupe quattro', 'model_RS 5 Sportback quattro',
       'model_RS 6 Avant quattro', 'model_RS 7 Sportback quattro',
       'model_RS Q8 quattro', 'model_RVR', 'model_RVR 4WD',
       'model_RX 350 AWD', 'model_RX 350 L AWD', 'model_RX 450h AWD',
       'model_RX 450h L AWD', 'model_Range Rover P360',
       'model_Range Rover P400', 'model_Range Rover P525',
       'model_Range Rover P525 LWB', 'model_Range Rover SVAutobiography',
       'model_Range Rover SVAutobiography LWB',
       'model_Range Rover Sport HST P400', 'model_Range Rover Sport P360',
       'model_Range Rover Sport P525', 'model_Range Rover Sport P575 SVR',
       'model_Ranger 4WD', 'model_Ranger 4WD (Without Stop-Start)',
       'model_Ranger 4WD Tremor', 'model_Renegade', 'model_Renegade 4X4',
       'model_Renegade 4X4 Trailhawk', 'model_Ridgeline AWD', 'model_Rio',
       'model_Rogue', 'model_Rogue AWD', 'model_Rogue AWD SL/Platinum',
       'model_S 500 4MATIC SWB Sedan', 'model_S 580 4MATIC LWB Sedan',
       'model_S3 Sedan quattro', 'model_S4 Sedan quattro',
       'model_S5 Cabriolet quattro', 'model_S5 Coupe quattro',
       'model_S5 Sportback quattro', 'model_S6 Sedan quattro',
       'model_S60 B5', 'model_S60 B5 AWD', 'model_S7 Sportback quattro',
       'model_S8 Sedan quattro', 'model_S90 B6 AWD',
       'model_SQ5 Sportback quattro', 'model_SQ5 quattro',
       'model_SQ7 quattro', 'model_SQ8 quattro', 'model_Santa Cruz AWD',
       'model_Santa Fe AWD', 'model_Santa Fe Hybrid', 'model_Seltos',
       'model_Seltos AWD', 'model_Sentra', 'model_Sentra SR',
       'model_Sequoia 4WD', 'model_Shelby GT500 Mustang', 'model_Sienna',
       'model_Sienna AWD', 'model_Sierra', 'model_Sierra 4WD',
       'model_Sierra 4WD (No DFM)', 'model_Sierra 4WD (No Stop-Start)',
       'model_Sierra 4WD (With Sport Mode)', 'model_Sierra 4WD FFV',
       'model_Sierra 4WD Mud Terrain Tire',
       'model_Sierra 4WD Mud Terrain Tire (No DFM)',
       'model_Sierra 4WD Mud Terrain Tire (No Stop-Start)',
       'model_Sierra 4WD Mud Terrain Tire FFV', 'model_Sierra FFV',
       'model_Silverado', 'model_Silverado 4WD',
       'model_Silverado 4WD (No DFM)',
       'model_Silverado 4WD (No Stop-Start)',
       'model_Silverado 4WD (With Sport Mode)',
       'model_Silverado 4WD Custom Trail Boss', 'model_Silverado 4WD FFV',
       'model_Silverado 4WD Mud Terrain Tire',
       'model_Silverado 4WD Mud Terrain Tire (No DFM)',
       'model_Silverado 4WD Mud Terrain Tire (No Stop-Start)',
       'model_Silverado 4WD Mud Terrain Tire FFV',
       'model_Silverado 4WD ZR2', 'model_Silverado FFV', 'model_Sonata',
       'model_Sonata Hybrid', 'model_Sorento AWD',
       'model_Sorento Hybrid AWD', 'model_Soul', 'model_Spark',
       'model_Sportage', 'model_Sportage AWD', 'model_Stelvio',
       'model_Stelvio AWD', 'model_Stelvio AWD Quadrifoglio',
       'model_Stinger AWD', 'model_Suburban',
       'model_Suburban (No Stop-Start)', 'model_Suburban 4WD',
       'model_Suburban 4WD (No Stop-Start)', 'model_TLX SH-AWD',
       'model_TLX SH-AWD A-SPEC', 'model_TLX Type S',
       'model_TLX Type S (Performance Tire)',
       'model_TT Coupe 45 TFSI quattro', 'model_TT RS Coupe quattro',
       'model_TT Roadster 45 TFSI quattro', 'model_TTS Coupe quattro',
       'model_Tacoma 4WD', 'model_Tacoma 4WD D-Cab TRD Off-Road/PRO',
       'model_Tahoe', 'model_Tahoe (No Stop-Start)', 'model_Tahoe 4WD',
       'model_Tahoe 4WD (No Stop-Start)', 'model_Taos',
       'model_Taos 4MOTION', 'model_Telluride AWD', 'model_Terrain',
       'model_Terrain AWD', 'model_Tiguan 4MOTION',
       'model_Tiguan R-Line 4MOTION', 'model_Trailblazer',
       'model_Trailblazer AWD', 'model_Transit Connect Van',
       'model_Transit Connect Van FFV', 'model_Transit Connect Wagon LWB',
       'model_Transit Connect Wagon LWB FFV', 'model_Traverse',
       'model_Traverse AWD', 'model_Trax', 'model_Trax AWD',
       'model_Tucson', 'model_Tucson AWD', 'model_Tucson Hybrid',
       'model_Tundra', 'model_Tundra 4WD', 'model_Tundra 4WD TRD',
       'model_Tundra Hybrid 4WD', 'model_Tundra Hybrid 4WD TRD PRO',
       'model_UX 200', 'model_UX 250h AWD', 'model_Urus',
       'model_V60 CC T5 AWD', 'model_V60 T6 AWD', 'model_V90 CC B6 AWD',
       'model_Vantage V8', 'model_Veloster N', 'model_Venue',
       'model_Venza AWD', 'model_Versa', 'model_WRX AWD',
       'model_Wagoneer 4X4', 'model_Wrangler JL 4X4',
       'model_Wrangler JL 4X4 eTorque', 'model_Wrangler JL Unlimited 4X4',
       'model_Wrangler JL Unlimited 4X4 EcoDiesel',
       'model_Wrangler JL Unlimited 4X4 Rubicon EcoDiesel',

In [51]:
t=pd.DataFrame(l,columns=c)

In [52]:
t

,make_Acura,make_Alfa Romeo,make_Aston Martin,make_Audi,make_BMW,make_Bentley,make_Bugatti,make_Buick,make_Cadillac,make_Chevrolet,...,transmission_AV6,transmission_AV7,transmission_AV8,transmission_M5,transmission_M6,transmission_M7,fueltype_D,fueltype_E,fueltype_X,fueltype_Z
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [53]:
l2=check.iloc[:,5:]

In [54]:
l2

   engine_size  cylinders  co2emission  co2 rating  SmogRating
0          2.4          4          200           6           3

In [55]:
final=pd.concat([l2,t],axis=1)

In [56]:
final

,engine_size,cylinders,co2emission,co2 rating,SmogRating,make_Acura,make_Alfa Romeo,make_Aston Martin,make_Audi,make_BMW,...,transmission_AV6,transmission_AV7,transmission_AV8,transmission_M5,transmission_M6,transmission_M7,fueltype_D,fueltype_E,fueltype_X,fueltype_Z
0,2.4,4,200,6,3,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [57]:
model=joblib.load("RFR.pkl")

In [58]:
model.predict(final)

array([8.58])